# general
prompt: "A pancake."
negative_prompt: ""
batch_size: 4
pixel: (512, 512)
num_steps: 50
guidance_scale: 100
seed: 42
work_dir: "Output/"

# guidance
#pretrain_model_id: "stabilityai/stable-diffusion-xl-base-1.0"
pretrain_model_id:  "CompVis/stable-diffusion-v1-4"
#pretrain_model_path: "~/autodl-tmp/CompVis/stable-diffusion-v1-4/"
pretrain_model_path: "~/autodl-tmp/CompVis/stable-diffusion-v1-4/"
fp16: true

